-- Apply once to the tiny_llm_benchmarks database before enabling --upload.
-- UUIDs are generated by train.py and reused in the SQL fallback file.
ALTER TABLE benchmark_runs
    ADD COLUMN upload_id CHAR(36) NULL AFTER run_id,
    ADD UNIQUE KEY uq_benchmark_runs_upload_id (upload_id);
